### PR TITLE
Scrolling shell down after entered command

### PR DESCRIPTION
**Pull request by YaroslavShapoval**
[Fixes issue #2](https://github.com/samdark/yii2-webshell/issues/2)

### CODE REVIEW

**Comment by samdark** [comment]
Instead of relying on timeouts, it could be done right after result is outputted in:
- https://github.com/samdark/yii2-webshell/blob/master/views/default/index.php#L20
- https://github.com/samdark/yii2-webshell/blob/master/views/default/index.php#L28
- https://github.com/samdark/yii2-webshell/blob/master/views/default/index.php#L33
- https://github.com/samdark/yii2-webshell/blob/master/views/default/index.php#L33
- https://github.com/samdark/yii2-webshell/blob/master/views/default/index.php#L38

**Comment by YaroslavShapoval** [comment]
You're right, it could be done this way.

How do you think, which way is better to implement this:

create function scroll-down and call it after last term.echo()

``` javascript
term.echo(json.result);
scrollDown();
...
term.echo('quit\tQuit web shell');
scrollDown();
... etc
```

or create function print(term, message), in the end of which scrolling down

``` javascript
function print(term, messages) {
    if (messages instanceof Array) {
        messages.forEach(function(message) {
            term.echo(message);
        });
    } else {
        term.echo(messages);
    }

    $('html, body').animate({ scrollTop: webshell.height() }, 'fast');
}
...
print(term, [
    'Available commands are:',
    '',
    "clear\tClear console",
    'help\tThis help text',
    'yii\tyii command',
    'quit\tQuit web shell'
]);
...
print(term, 'Unknown command.');
```

**Comment by samdark** [comment]
First way is more straightforward.

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
